import { PageHeading } from "@/shared/ui/page-heading";
import { UserNavbar, UserNavbarModal } from "@/widgets/user-navbar";
import type { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: "Аккаунт",
  description: "Generated by create next app",
};

export default function UserProfileLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="w-full flex flex-col gap-10">
      <PageHeading title="Личный кабинет" endContent={<UserNavbarModal />} />
      <div className="gap-8 w-full max-w-screen-2xl mx-auto grid md:grid-cols-[2fr_8fr] px-6">
        <UserNavbar />
        {children}
      </div>
    </div>
  );
}
