import { UserNavbar } from "@/widgets/user-navbar";
import type { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: "Аккаунт",
  description: "Generated by create next app",
};

export default function UserProfileLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="w-full max-w-screen-2xl self-center grid lg:grid-cols-[2fr_8fr] px-6">
      <UserNavbar />
      {children}
    </div>
  );
}
